services:
  - type: web
    name: victor-volleyball
    env: node
    region: singapore
    plan: free
    buildCommand: pnpm install && pnpm run build
    startCommand: pnpm exec tsx scripts/setup-db.ts && pnpm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BASIC_AUTH_PASSWORD
        value: meikei
      - key: DATABASE_URL
        sync: false
